name: Setup and Commit

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run setup script
        run: |
          chmod +x setup.sh
          ./setup.sh

      - name: Commit changes
        run: |
          git config --global user.name "Rekt-Developer"
          git config --global user.email "your-email@example.com"
          git add .
          git commit -m "Setup project via GitHub Actions" || echo "Nothing to commit"
          git push
